# Generated by Django 4.2.3 on 2023-08-06 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_statuscrm_order_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentCrm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coment_text', models.TextField(verbose_name='Comment text')),
                ('coment_dt', models.DateTimeField(auto_now=True, verbose_name='Date')),
                ('coment_binding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.order', verbose_name='Application')),
            ],
            options={
                'verbose_name': 'Coment',
                'verbose_name_plural': 'Coments',
            },
        ),
    ]
